#ifndef _PARAMS_H
#define _PARAMS_H

#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <inttypes.h>

#ifndef XPARAMS
#error "There is no definion for the X-macro before the include of params.h. Define XPARAMS(X)"
#endif

#define TYPE_uint32_t PARAM_TYPE_UINT32
#define TYPE_size_t   PARAM_TYPE_SIZET
#define TYPE_double   PARAM_TYPE_DOUBLE
#define TYPE_char_ptr PARAM_TYPE_STRING

typedef enum {
	PARAM_TYPE_UINT32,
	PARAM_TYPE_DOUBLE,
	PARAM_TYPE_STRING
} ParamType;

typedef struct {
	#define DECLARE_FIELD(name, type, default_value) type name;
	XPARAMS(DECLARE_FIELD)
	#undef DECLARE_FIELD
	size_t count;
} Parameters;

typedef struct {
	const char* name_env;
	void* value;
	ParamType type;
	bool found;
} ParameterDescriptor;

static inline void script_default_generate() {
	FILE* fp = fopen("run_default.sh", "w");

	fprintf(fp, "#!/bin/bash\n");
	fprintf(fp, "# Generated by script_default_generate in params.h\n\n");

	#define PRINT_PARAM_uint32_t(name, type, default_value) \
		fprintf(fp, "export PARAM_" #name "=%lu\n", (unsigned long)default_value);
	#define PRINT_PARAM_size_t(name, type, default_value) \
		fprintf(fp, "export PARAM_" #name "=%zu\n", (size_t)default_value);
	#define PRINT_PARAM_double(name, type, default_value) \
		fprintf(fp, "export PARAM_" #name "=%g\n", (double)default_value);
	#define PRINT_PARAM_char_ptr(name, type, default_value) \
		fprintf(fp, "export PARAM_" #name "=%s", #default_value);

	#define PRINT_PARAM(name, type, default_value) PRINT_PARAM_##type(name, type, default_value)
	XPARAMS(PRINT_PARAM)
	#undef PRINT_PARAM

	fprintf(fp, "\n./a.out");

	chmod("run_default.sh", (mode_t)0755);
	fclose(fp);
}
static inline Parameters* parameters_read() {

	Parameters* par = calloc((size_t)1, sizeof *par);

	ParameterDescriptor param_descs[] = {
		#define ENVNAME(name) "PARAM_" #name
		#define DECLARE_DESCRIPTOR(name, type, default_value) { ENVNAME(name), &(par->name), \
							 TYPE_##type, false },
		XPARAMS(DECLARE_DESCRIPTOR)
		#undef DECLARE_DESCRIPTOR
	};
	const size_t param_count = sizeof(param_descs) / sizeof(param_descs[0]);
	par->count = param_count;

	bool error_flag = false;
	for (size_t i = 0; i < param_count; i++) {
		char* env = getenv(param_descs[i].name_env);
		if (env != NULL) {
			switch (param_descs[i].type) {
			case PARAM_TYPE_UINT32:
				*(uint32_t*) param_descs[i].value = strtol(env, NULL, 10);
				break;
			case PARAM_TYPE_SIZET:
				// TODO: add checks for overlflow etc.
				char* endptr = NULL;
				uintmax_t tmp = strtoumax(env, &endptr, 10);
				*(size_t*) param_descs[i].value = (size_t)tmp;
				break;
			case PARAM_TYPE_DOUBLE:
				*(double*) param_descs[i].value = strtod(env, NULL);
				break;
			case PARAM_TYPE_STRING:
				*(char**) param_descs[i].value = env;
				break;
			default:
				fprintf(stderr, "Error in type dispatch in parameters_read()!\n");
				break;
			}
			param_descs[i].found = true;

		} else {
			error_flag = true;
			param_descs[i].found = false;
		}
	}

	if (error_flag == 1) {
		for (size_t i = 0; i < param_count; i++) {
			if (param_descs[i].found == false) {
				fprintf(stderr, "Error reading in parameter %s. Make sure to export it.\n",
						param_descs[i].name_env);
			}
		}
 		fprintf(stderr, "We generate a default run script 'run_default.sh'. Start the simulation via ./run_default.sh.\n");
		script_default_generate();
		exit(-1);
	}

	return par;
}

static inline void parameters_free(Parameters* par) {
	if (par) free(par);
}

#endif

